/**
 * Fallback Data — Demo & Resilience Layer
 * =========================================
 * Realistic sample data used when:
 *   1. Database is unreachable (resilience)
 *   2. DEMO_MODE=true is set (showcasing)
 *
 * IMPORTANT: This file does NOT modify any database models,
 * schemas, or existing business logic. It is a read-only
 * backup data source.
 */

// ─── Demo Mode Flag ──────────────────────────────────────────

export const IS_DEMO_MODE = process.env.DEMO_MODE === "true";

// ─── Therapists ──────────────────────────────────────────────

export const fallbackTherapists = [
  {
    id: "demo-therapist-1",
    userId: "demo-user-1",
    user: { id: "demo-user-1", name: "Dr. Priya Sharma", email: "priya@example.com", avatar: null },
    specializations: ["Orthopedic", "Sports Injury"],
    experience: 12,
    bio: "Senior physiotherapist with 12+ years of experience in orthopedic rehabilitation and sports injury recovery. Specializes in post-surgical rehab for knee and shoulder injuries.",
    qualifications: "BPT, MPT (Orthopedics), MIAP",
    hourlyRate: 800,
    homeVisit: true,
    clinicVisit: true,
    onlineConsult: true,
    rating: 4.9,
    reviewCount: 142,
    verified: true,
    latitude: 23.0225,
    longitude: 72.5714,
    address: "Satellite Road, Ahmedabad",
    city: "Ahmedabad",
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-therapist-2",
    userId: "demo-user-2",
    user: { id: "demo-user-2", name: "Dr. Rajesh Patel", email: "rajesh@example.com", avatar: null },
    specializations: ["Neurological", "Geriatric"],
    experience: 15,
    bio: "Expert in neuro-rehabilitation and geriatric physiotherapy. Passionate about helping stroke survivors and elderly patients regain independence through evidence-based therapy.",
    qualifications: "BPT, MPT (Neurology), PhD",
    hourlyRate: 1000,
    homeVisit: true,
    clinicVisit: true,
    onlineConsult: false,
    rating: 4.8,
    reviewCount: 98,
    verified: true,
    latitude: 23.0350,
    longitude: 72.5600,
    address: "Vastrapur, Ahmedabad",
    city: "Ahmedabad",
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-therapist-3",
    userId: "demo-user-3",
    user: { id: "demo-user-3", name: "Dr. Anita Desai", email: "anita@example.com", avatar: null },
    specializations: ["Women's Health", "Post-Surgical"],
    experience: 8,
    bio: "Specializes in women's health physiotherapy including prenatal/postnatal care, pelvic floor rehabilitation, and post-surgical recovery for women of all ages.",
    qualifications: "BPT, MPT (Women's Health)",
    hourlyRate: 700,
    homeVisit: true,
    clinicVisit: true,
    onlineConsult: true,
    rating: 4.9,
    reviewCount: 76,
    verified: true,
    latitude: 23.0100,
    longitude: 72.5200,
    address: "Navrangpura, Ahmedabad",
    city: "Ahmedabad",
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-therapist-4",
    userId: "demo-user-4",
    user: { id: "demo-user-4", name: "Dr. Vikram Singh", email: "vikram@example.com", avatar: null },
    specializations: ["Sports Injury", "Spine & Back"],
    experience: 10,
    bio: "Former sports team physiotherapist with deep expertise in spine rehabilitation, chronic back pain management, and athletic performance recovery.",
    qualifications: "BPT, MSc Sports Medicine, CSCS",
    hourlyRate: 900,
    homeVisit: false,
    clinicVisit: true,
    onlineConsult: true,
    rating: 4.7,
    reviewCount: 115,
    verified: true,
    latitude: 23.0400,
    longitude: 72.5500,
    address: "SG Highway, Ahmedabad",
    city: "Ahmedabad",
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-therapist-5",
    userId: "demo-user-5",
    user: { id: "demo-user-5", name: "Dr. Meera Joshi", email: "meera@example.com", avatar: null },
    specializations: ["Pediatric", "Neurological"],
    experience: 9,
    bio: "Dedicated pediatric physiotherapist helping children with developmental delays, cerebral palsy, and neurological conditions through play-based therapy.",
    qualifications: "BPT, MPT (Pediatrics)",
    hourlyRate: 750,
    homeVisit: true,
    clinicVisit: true,
    onlineConsult: true,
    rating: 4.8,
    reviewCount: 63,
    verified: true,
    latitude: 23.0500,
    longitude: 72.5800,
    address: "Thaltej, Ahmedabad",
    city: "Ahmedabad",
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-therapist-6",
    userId: "demo-user-6",
    user: { id: "demo-user-6", name: "Dr. Karan Mehta", email: "karan@example.com", avatar: null },
    specializations: ["Chronic Pain", "Cardiopulmonary"],
    experience: 7,
    bio: "Focuses on chronic pain management and cardiopulmonary rehabilitation. Uses modern techniques like dry needling, cupping therapy, and breathing exercises.",
    qualifications: "BPT, MPT (Cardiopulmonary)",
    hourlyRate: 650,
    homeVisit: true,
    clinicVisit: false,
    onlineConsult: true,
    rating: 4.6,
    reviewCount: 54,
    verified: true,
    latitude: 23.0150,
    longitude: 72.5900,
    address: "Maninagar, Ahmedabad",
    city: "Ahmedabad",
    createdAt: new Date().toISOString(),
  },
];

// ─── Products ────────────────────────────────────────────────

export const fallbackProducts = [
  {
    id: "demo-product-1",
    name: "ProRelief Therapeutic Massage Gun",
    slug: "prorelief-massage-gun",
    description: "Professional-grade percussion massage gun with 6 speed settings and 4 interchangeable heads. Designed for deep tissue muscle recovery and pain relief.",
    price: 4999,
    salePrice: 3499,
    category: "MASSAGE_GUNS",
    images: [],
    inStock: true,
    stockCount: 25,
    rating: 4.7,
    features: ["6 Speed Settings", "4 Massage Heads", "2400mAh Battery", "Ultra Quiet Motor", "Carrying Case Included"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-product-2",
    name: "OrthoFlex Posture Corrector Belt",
    slug: "orthoflex-posture-corrector",
    description: "Doctor-recommended posture corrector for upper back, neck, and shoulders. Adjustable, breathable, and comfortable for all-day wear.",
    price: 1299,
    salePrice: 999,
    category: "POSTURE_CORRECTORS",
    images: [],
    inStock: true,
    stockCount: 50,
    rating: 4.5,
    features: ["Adjustable Straps", "Breathable Fabric", "Unisex Design", "Invisible Under Clothes", "Doctor Recommended"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-product-3",
    name: "HeatWave Pain Relief Patch (Pack of 10)",
    slug: "heatwave-pain-relief-patch",
    description: "Advanced heat therapy patches for targeted muscle and joint pain relief. Provides up to 8 hours of continuous soothing warmth.",
    price: 599,
    salePrice: null,
    category: "PAIN_RELIEF",
    images: [],
    inStock: true,
    stockCount: 100,
    rating: 4.3,
    features: ["8-Hour Relief", "Drug-Free", "Odor-Free", "Flexible Fit", "Pack of 10"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-product-4",
    name: "FlexiStep Orthopedic Slippers",
    slug: "flexistep-orthopedic-slippers",
    description: "Premium orthopedic slippers with memory foam insoles and arch support. Designed by physiotherapists for everyday comfort and foot health.",
    price: 1999,
    salePrice: 1499,
    category: "SLIPPERS",
    images: [],
    inStock: true,
    stockCount: 35,
    rating: 4.6,
    features: ["Memory Foam Insole", "Arch Support", "Anti-Skid Sole", "Lightweight", "Available in 5 Colors"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-product-5",
    name: "PhysioBand Resistance Set (5 Levels)",
    slug: "physioband-resistance-set",
    description: "Professional-grade resistance band set with 5 resistance levels. Perfect for physiotherapy exercises, strength training, and home workouts.",
    price: 899,
    salePrice: 699,
    category: "EXERCISE_EQUIPMENT",
    images: [],
    inStock: true,
    stockCount: 80,
    rating: 4.8,
    features: ["5 Resistance Levels", "Natural Latex", "Carry Bag", "Exercise Guide", "Physiotherapist Approved"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-product-6",
    name: "CryoGel Ice Pack Wrap (Knee/Shoulder)",
    slug: "cryogel-ice-pack-wrap",
    description: "Reusable gel ice pack with adjustable wrap for knee, shoulder, and joint injuries. Provides targeted cold therapy for pain and swelling reduction.",
    price: 799,
    salePrice: null,
    category: "ACCESSORIES",
    images: [],
    inStock: true,
    stockCount: 45,
    rating: 4.4,
    features: ["Reusable Gel Pack", "Adjustable Wrap", "Hot & Cold Therapy", "Universal Fit", "Medical Grade"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// ─── Clinics ─────────────────────────────────────────────────

export const fallbackClinics = [
  {
    id: "demo-clinic-1",
    name: "PhysioJoy Elite Clinic",
    address: "203 Titanium City Center, Satellite Road, Ahmedabad 380015",
    city: "Ahmedabad",
    phone: "+91 79 2685 1234",
    email: "elite@physiojoy.in",
    latitude: 23.0225,
    longitude: 72.5714,
    description: "State-of-the-art physiotherapy clinic with advanced equipment and certified specialists.",
    services: ["Orthopedic", "Sports Injury", "Post-Surgical", "Spine & Back"],
    images: [],
    rating: 4.8,
    timings: "Mon-Sat: 8AM - 8PM",
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-clinic-2",
    name: "SpineAlign Physiotherapy Center",
    address: "45 Shilp Epitome, Vastrapur, Ahmedabad 380054",
    city: "Ahmedabad",
    phone: "+91 79 2640 5678",
    email: "info@spinealign.in",
    latitude: 23.0350,
    longitude: 72.5600,
    description: "Specialized spine and back pain rehabilitation center with expert therapists.",
    services: ["Spine & Back", "Chronic Pain", "Neurological", "Geriatric"],
    images: [],
    rating: 4.7,
    timings: "Mon-Sat: 9AM - 7PM",
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-clinic-3",
    name: "ActiveLife Rehab Studio",
    address: "12 Prahladnagar Garden Road, Ahmedabad 380015",
    city: "Ahmedabad",
    phone: "+91 79 2680 9012",
    email: "hello@activelife.in",
    latitude: 23.0100,
    longitude: 72.5200,
    description: "Modern rehabilitation studio combining traditional physiotherapy with advanced recovery technology.",
    services: ["Sports Injury", "Women's Health", "Pediatric", "Chronic Pain"],
    images: [],
    rating: 4.9,
    timings: "Mon-Sun: 7AM - 9PM",
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

// ─── Physio Dance Videos ─────────────────────────────────────

export const fallbackVideos = [
  {
    id: "demo-video-1",
    title: "Morning Mobility Flow",
    description: "A gentle 15-minute therapeutic dance routine to improve morning mobility and reduce stiffness.",
    videoUrl: "https://example.com/videos/morning-flow",
    thumbnail: "",
    duration: "15:00",
    category: "Mobility",
    difficulty: "Beginner",
    instructor: "Dr. Priya Sharma",
    views: 12450,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-video-2",
    title: "Back Pain Relief Dance",
    description: "Targeted dance movements designed by physiotherapists to alleviate lower back pain and improve flexibility.",
    videoUrl: "https://example.com/videos/back-relief",
    thumbnail: "",
    duration: "20:00",
    category: "Pain Relief",
    difficulty: "Intermediate",
    instructor: "Dr. Rajesh Patel",
    views: 8930,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-video-3",
    title: "Shoulder Rehab Groove",
    description: "Fun therapeutic movements for shoulder rehabilitation. Great for frozen shoulder and post-injury recovery.",
    videoUrl: "https://example.com/videos/shoulder-groove",
    thumbnail: "",
    duration: "18:00",
    category: "Rehabilitation",
    difficulty: "Beginner",
    instructor: "Dr. Anita Desai",
    views: 6720,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-video-4",
    title: "Full Body Stretch Dance",
    description: "Complete body stretching routine set to music. Improves overall flexibility and reduces muscle tension.",
    videoUrl: "https://example.com/videos/full-stretch",
    thumbnail: "",
    duration: "25:00",
    category: "Flexibility",
    difficulty: "Advanced",
    instructor: "Dr. Vikram Singh",
    views: 15280,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];
